/**
 * Default ticket templates seeded for new tenants.
 * Used during onboarding or when tenant requests defaults.
 */
export const DEFAULT_TEMPLATES = [
  {
    name: "Payment Issue",
    description: "Customer reports a payment problem",
    issueType: "billing",
    priority: "HIGH" as const,
    defaultTags: ["billing", "payment"],
    bodyTemplate: "Customer is experiencing a payment issue.\n\nDetails:\n- Transaction ID:\n- Amount:\n- Date:\n- Error message (if any):",
    sortOrder: 1,
  },
  {
    name: "Account Access",
    description: "Customer cannot access their account",
    issueType: "account",
    priority: "HIGH" as const,
    defaultTags: ["account", "access"],
    bodyTemplate: "Customer is unable to access their account.\n\nDetails:\n- Email address:\n- Error message:\n- Last successful login:",
    sortOrder: 2,
  },
  {
    name: "Bug Report",
    description: "Customer reports a software bug",
    issueType: "technical",
    priority: "MEDIUM" as const,
    defaultTags: ["bug", "technical"],
    bodyTemplate: "Bug report:\n\nSteps to reproduce:\n1. \n2. \n3. \n\nExpected behavior:\n\nActual behavior:\n\nBrowser/Device:",
    sortOrder: 3,
  },
  {
    name: "Feature Request",
    description: "Customer suggests a new feature",
    issueType: "feedback",
    priority: "LOW" as const,
    defaultTags: ["feature-request", "feedback"],
    bodyTemplate: "Feature request:\n\nDescription:\n\nUse case:\n\nExpected benefit:",
    sortOrder: 4,
  },
  {
    name: "Billing Question",
    description: "General billing or invoice inquiry",
    issueType: "billing",
    priority: "MEDIUM" as const,
    defaultTags: ["billing", "invoice"],
    bodyTemplate: "Billing inquiry:\n\nQuestion:\n\nAccount/Invoice reference:",
    sortOrder: 5,
  },
  {
    name: "Refund Request",
    description: "Customer requests a refund",
    issueType: "billing",
    priority: "HIGH" as const,
    defaultTags: ["billing", "refund"],
    bodyTemplate: "Refund request:\n\nTransaction/Order ID:\nAmount:\nReason for refund:\nPreferred refund method:",
    sortOrder: 6,
  },
  {
    name: "Technical Support",
    description: "General technical assistance needed",
    issueType: "technical",
    priority: "MEDIUM" as const,
    defaultTags: ["technical", "support"],
    bodyTemplate: "Technical support request:\n\nIssue description:\n\nSteps already tried:\n\nEnvironment (browser, OS, device):",
    sortOrder: 7,
  },
  {
    name: "General Inquiry",
    description: "General question or information request",
    issueType: "general",
    priority: "LOW" as const,
    defaultTags: ["general"],
    bodyTemplate: "General inquiry:\n\nQuestion/Request:",
    sortOrder: 8,
  },
  {
    name: "Urgent Escalation",
    description: "Critical issue requiring immediate attention",
    issueType: "escalation",
    priority: "CRITICAL" as const,
    defaultTags: ["urgent", "escalation"],
    bodyTemplate: "URGENT ESCALATION\n\nImpact:\n- Number of users affected:\n- Business impact:\n- Started at:\n\nDescription:\n\nWorkaround (if any):",
    sortOrder: 9,
  },
  {
    name: "Feedback",
    description: "General customer feedback",
    issueType: "feedback",
    priority: "LOW" as const,
    defaultTags: ["feedback"],
    bodyTemplate: "Customer feedback:\n\nCategory (product/service/support):\n\nFeedback:\n\nSuggestion (if any):",
    sortOrder: 10,
  },
];
