/**
 * @module seeds/industryPacks
 * Seed data for the 7 industry starter packs.
 * Import and upsert via a migration script or admin endpoint.
 */

export const INDUSTRY_PACKS = [
  {
    slug: "ecommerce",
    name: "E-Commerce",
    description: "Support templates for online retail — orders, payments, refunds, and shipping.",
    icon: "\uD83D\uDED2",
    issueTypes: [
      { name: "Order issue", description: "Problems with order placement or status", defaultPriority: "HIGH" },
      { name: "Payment failed", description: "Payment processing errors or declines", defaultPriority: "HIGH" },
      { name: "Refund", description: "Refund requests and processing", defaultPriority: "MEDIUM" },
      { name: "Shipping delay", description: "Late or delayed shipments", defaultPriority: "MEDIUM" },
      { name: "Product defect", description: "Defective or damaged products received", defaultPriority: "HIGH" },
      { name: "Return", description: "Product return requests", defaultPriority: "MEDIUM" },
    ],
    responseTemplates: [
      {
        name: "Order Issue Acknowledgement",
        subject: "We're looking into your order issue",
        body: "Hi {{customerName}},\n\nThank you for reaching out about your order #{{orderId}}. We understand how important this is and our team is reviewing it now.\n\nWe'll get back to you within 4 hours with an update.\n\nBest regards,\n{{agentName}}",
        issueType: "Order issue",
      },
      {
        name: "Refund Confirmation",
        subject: "Your refund has been initiated",
        body: "Hi {{customerName}},\n\nWe've initiated a refund for your order #{{orderId}}. Please allow 5-10 business days for the amount to appear in your account.\n\nIf you have any questions, don't hesitate to reach out.\n\nBest regards,\n{{agentName}}",
        issueType: "Refund",
      },
      {
        name: "Shipping Delay Update",
        subject: "Update on your shipment",
        body: "Hi {{customerName}},\n\nWe apologize for the delay with your shipment. Our logistics team is working to expedite delivery. Your new estimated delivery date is {{estimatedDate}}.\n\nThank you for your patience.\n\nBest regards,\n{{agentName}}",
        issueType: "Shipping delay",
      },
      {
        name: "Return Instructions",
        subject: "How to return your item",
        body: "Hi {{customerName}},\n\nWe're sorry the product didn't meet your expectations. Here's how to return it:\n\n1. Pack the item in its original packaging\n2. Use the prepaid label attached to this email\n3. Drop it off at your nearest shipping location\n\nOnce received, we'll process your refund within 3-5 business days.\n\nBest regards,\n{{agentName}}",
        issueType: "Return",
      },
    ],
    slaTargets: { firstResponseMinutes: 240, resolutionMinutes: 1440 },
    isActive: true,
    sortOrder: 0,
  },
  {
    slug: "saas",
    name: "SaaS",
    description: "Templates for software-as-a-service — bugs, features, access, and integrations.",
    icon: "\uD83D\uDCBB",
    issueTypes: [
      { name: "Bug report", description: "Software bugs and unexpected behavior", defaultPriority: "HIGH" },
      { name: "Feature request", description: "Suggestions for new features or improvements", defaultPriority: "LOW" },
      { name: "Account access", description: "Login issues, password resets, and account lockouts", defaultPriority: "HIGH" },
      { name: "Billing", description: "Subscription and billing inquiries", defaultPriority: "MEDIUM" },
      { name: "Integration", description: "Third-party integration setup and issues", defaultPriority: "MEDIUM" },
      { name: "Data export", description: "Requests for data export or migration", defaultPriority: "LOW" },
    ],
    responseTemplates: [
      {
        name: "Bug Report Acknowledgement",
        subject: "We've received your bug report",
        body: "Hi {{customerName}},\n\nThank you for reporting this issue. Our engineering team has been notified and is investigating.\n\nBug ID: {{ticketId}}\nPriority: {{priority}}\n\nWe'll update you within 2 hours.\n\nBest regards,\n{{agentName}}",
        issueType: "Bug report",
      },
      {
        name: "Feature Request Logged",
        subject: "Your feature request has been logged",
        body: "Hi {{customerName}},\n\nThank you for your suggestion! We've added it to our product backlog and will evaluate it for an upcoming release.\n\nWe appreciate your input in making our product better.\n\nBest regards,\n{{agentName}}",
        issueType: "Feature request",
      },
      {
        name: "Account Access Recovery",
        subject: "Restoring your account access",
        body: "Hi {{customerName}},\n\nWe understand you're having trouble accessing your account. Here are the steps to regain access:\n\n1. Visit {{resetUrl}}\n2. Enter your registered email address\n3. Follow the password reset instructions\n\nIf you continue to experience issues, we can assist you directly.\n\nBest regards,\n{{agentName}}",
        issueType: "Account access",
      },
    ],
    slaTargets: { firstResponseMinutes: 120, resolutionMinutes: 720 },
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: "fintech",
    name: "Fintech",
    description: "Financial services support — transactions, KYC, fraud, and account security.",
    icon: "\uD83C\uDFE6",
    issueTypes: [
      { name: "Transaction dispute", description: "Disputed or unauthorized transactions", defaultPriority: "CRITICAL" },
      { name: "KYC", description: "Know Your Customer verification issues", defaultPriority: "HIGH" },
      { name: "Card block", description: "Blocked or frozen card issues", defaultPriority: "CRITICAL" },
      { name: "Transfer delay", description: "Delayed bank transfers or payments", defaultPriority: "HIGH" },
      { name: "Account freeze", description: "Frozen or restricted accounts", defaultPriority: "CRITICAL" },
      { name: "Fraud", description: "Suspected fraudulent activity on account", defaultPriority: "CRITICAL" },
    ],
    responseTemplates: [
      {
        name: "Transaction Dispute Received",
        subject: "Your transaction dispute is being reviewed",
        body: "Hi {{customerName}},\n\nWe've received your dispute for transaction {{transactionId}}. Our fraud team is reviewing this with the highest priority.\n\nPlease do not share your account credentials with anyone. We will never ask for your PIN or password.\n\nExpect an update within 1 hour.\n\nBest regards,\n{{agentName}}",
        issueType: "Transaction dispute",
      },
      {
        name: "KYC Verification Required",
        subject: "Additional verification needed for your account",
        body: "Hi {{customerName}},\n\nTo comply with regulatory requirements, we need to verify your identity. Please provide:\n\n1. A valid government-issued ID\n2. Proof of address (utility bill or bank statement, dated within 3 months)\n\nYou can upload these securely through your account settings.\n\nBest regards,\n{{agentName}}",
        issueType: "KYC",
      },
      {
        name: "Fraud Alert Response",
        subject: "Important: Suspicious activity on your account",
        body: "Hi {{customerName}},\n\nWe've detected unusual activity on your account and have temporarily restricted certain functions for your protection.\n\nPlease review your recent transactions and confirm whether they were authorized. If you did not make these transactions, we will initiate a reversal immediately.\n\nBest regards,\n{{agentName}}",
        issueType: "Fraud",
      },
      {
        name: "Card Block Resolution",
        subject: "Your card block has been reviewed",
        body: "Hi {{customerName}},\n\nWe've reviewed the block on your card ending in {{lastFour}}. {{resolution}}\n\nIf you need further assistance, please don't hesitate to contact us.\n\nBest regards,\n{{agentName}}",
        issueType: "Card block",
      },
    ],
    slaTargets: { firstResponseMinutes: 60, resolutionMinutes: 240 },
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    description: "Patient and provider support — appointments, billing, records, and prescriptions.",
    icon: "\uD83C\uDFE5",
    issueTypes: [
      { name: "Appointment", description: "Scheduling, rescheduling, or cancellation of appointments", defaultPriority: "MEDIUM" },
      { name: "Billing", description: "Medical billing inquiries and disputes", defaultPriority: "MEDIUM" },
      { name: "Insurance", description: "Insurance coverage and claim questions", defaultPriority: "MEDIUM" },
      { name: "Records", description: "Medical records requests and access", defaultPriority: "HIGH" },
      { name: "Prescription", description: "Prescription refills and questions", defaultPriority: "HIGH" },
      { name: "Referral", description: "Specialist referral requests", defaultPriority: "MEDIUM" },
    ],
    responseTemplates: [
      {
        name: "Appointment Confirmation",
        subject: "Your appointment details",
        body: "Hi {{customerName}},\n\nYour appointment has been {{action}}.\n\nDate: {{appointmentDate}}\nTime: {{appointmentTime}}\nProvider: {{providerName}}\n\nPlease arrive 15 minutes early with your ID and insurance card.\n\nBest regards,\n{{agentName}}",
        issueType: "Appointment",
      },
      {
        name: "Records Request Processing",
        subject: "Your medical records request is being processed",
        body: "Hi {{customerName}},\n\nWe've received your request for medical records. In compliance with HIPAA regulations, we'll process this within 30 days.\n\nYou'll receive a secure link to download your records once they're ready.\n\nBest regards,\n{{agentName}}",
        issueType: "Records",
      },
      {
        name: "Prescription Refill Status",
        subject: "Update on your prescription refill",
        body: "Hi {{customerName}},\n\nYour prescription refill for {{medicationName}} has been {{status}}. {{additionalInfo}}\n\nIf you have questions about your medication, please consult your healthcare provider.\n\nBest regards,\n{{agentName}}",
        issueType: "Prescription",
      },
    ],
    slaTargets: { firstResponseMinutes: 240, resolutionMinutes: 1440 },
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: "professional-services",
    name: "Professional Services",
    description: "Consulting and services support — engagements, invoices, deliverables, and contracts.",
    icon: "\uD83D\uDCBC",
    issueTypes: [
      { name: "Engagement scope", description: "Questions about project scope and deliverables", defaultPriority: "MEDIUM" },
      { name: "Invoice", description: "Invoice queries, adjustments, and payment issues", defaultPriority: "MEDIUM" },
      { name: "Deliverable", description: "Deliverable status, quality, and revision requests", defaultPriority: "HIGH" },
      { name: "Contract", description: "Contract terms, amendments, and renewal", defaultPriority: "MEDIUM" },
      { name: "Scheduling", description: "Meeting and milestone scheduling", defaultPriority: "LOW" },
    ],
    responseTemplates: [
      {
        name: "Engagement Scope Clarification",
        subject: "Clarification on your engagement scope",
        body: "Hi {{customerName}},\n\nThank you for reaching out about your engagement. We've reviewed your query and here's what's covered under your current scope:\n\n{{scopeDetails}}\n\nIf you'd like to discuss changes, we can schedule a call with your account manager.\n\nBest regards,\n{{agentName}}",
        issueType: "Engagement scope",
      },
      {
        name: "Invoice Clarification",
        subject: "Regarding your invoice inquiry",
        body: "Hi {{customerName}},\n\nThank you for your inquiry about invoice #{{invoiceNumber}}. {{invoiceDetails}}\n\nIf you need further clarification, please don't hesitate to ask.\n\nBest regards,\n{{agentName}}",
        issueType: "Invoice",
      },
      {
        name: "Deliverable Status Update",
        subject: "Update on your deliverable",
        body: "Hi {{customerName}},\n\nHere's the latest on your deliverable:\n\nStatus: {{deliverableStatus}}\nEstimated completion: {{estimatedDate}}\n\nWe'll keep you informed of any changes. Thank you for your patience.\n\nBest regards,\n{{agentName}}",
        issueType: "Deliverable",
      },
    ],
    slaTargets: { firstResponseMinutes: 480, resolutionMinutes: 2880 },
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: "education",
    name: "Education",
    description: "Academic and EdTech support — enrollment, grades, platform access, and financial aid.",
    icon: "\uD83C\uDF93",
    issueTypes: [
      { name: "Enrollment", description: "Course enrollment and registration issues", defaultPriority: "MEDIUM" },
      { name: "Grade dispute", description: "Grade appeals and correction requests", defaultPriority: "HIGH" },
      { name: "Platform access", description: "LMS and learning platform access issues", defaultPriority: "HIGH" },
      { name: "Financial aid", description: "Scholarships, grants, and financial assistance queries", defaultPriority: "MEDIUM" },
      { name: "Transcript", description: "Official transcript requests", defaultPriority: "LOW" },
      { name: "Accommodation", description: "Disability accommodation and special needs requests", defaultPriority: "HIGH" },
    ],
    responseTemplates: [
      {
        name: "Enrollment Confirmation",
        subject: "Your enrollment request has been received",
        body: "Hi {{customerName}},\n\nWe've received your enrollment request for {{courseName}}. Our registrar's office will process this within 3 business days.\n\nYou'll receive a confirmation email once your enrollment is finalized.\n\nBest regards,\n{{agentName}}",
        issueType: "Enrollment",
      },
      {
        name: "Grade Dispute Acknowledgement",
        subject: "Your grade dispute is under review",
        body: "Hi {{customerName}},\n\nWe've forwarded your grade dispute for {{courseName}} to the academic review committee. The review process typically takes 5-7 business days.\n\nYou'll be notified of the outcome via email.\n\nBest regards,\n{{agentName}}",
        issueType: "Grade dispute",
      },
      {
        name: "Platform Access Recovery",
        subject: "Restoring your platform access",
        body: "Hi {{customerName}},\n\nWe're working on restoring your access to the learning platform. In the meantime, try these steps:\n\n1. Clear your browser cache\n2. Try an incognito/private window\n3. Use the password reset link: {{resetUrl}}\n\nIf the issue persists, we'll escalate to our IT team.\n\nBest regards,\n{{agentName}}",
        issueType: "Platform access",
      },
      {
        name: "Financial Aid Information",
        subject: "Regarding your financial aid inquiry",
        body: "Hi {{customerName}},\n\nThank you for reaching out about financial aid. Here are the next steps:\n\n1. Complete the financial aid application at {{applicationUrl}}\n2. Submit required documents by {{deadline}}\n3. Our financial aid office will review within 2-3 weeks\n\nBest regards,\n{{agentName}}",
        issueType: "Financial aid",
      },
    ],
    slaTargets: { firstResponseMinutes: 1440, resolutionMinutes: 4320 },
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: "logistics",
    name: "Logistics",
    description: "Supply chain and delivery support — shipments, tracking, customs, and route changes.",
    icon: "\uD83D\uDE9A",
    issueTypes: [
      { name: "Shipment delay", description: "Delayed or overdue shipments", defaultPriority: "HIGH" },
      { name: "Damaged goods", description: "Items damaged in transit", defaultPriority: "HIGH" },
      { name: "Tracking", description: "Shipment tracking and status inquiries", defaultPriority: "MEDIUM" },
      { name: "Pickup", description: "Pickup scheduling and issues", defaultPriority: "MEDIUM" },
      { name: "Customs", description: "Customs clearance delays and documentation", defaultPriority: "HIGH" },
      { name: "Route change", description: "Delivery route or address changes", defaultPriority: "MEDIUM" },
    ],
    responseTemplates: [
      {
        name: "Shipment Delay Notification",
        subject: "Update on your shipment delay",
        body: "Hi {{customerName}},\n\nWe're aware of the delay affecting shipment #{{shipmentId}}. The current status is:\n\nOriginal ETA: {{originalEta}}\nRevised ETA: {{revisedEta}}\nReason: {{delayReason}}\n\nWe're working to expedite delivery and will keep you updated.\n\nBest regards,\n{{agentName}}",
        issueType: "Shipment delay",
      },
      {
        name: "Damaged Goods Claim",
        subject: "Your damage claim has been filed",
        body: "Hi {{customerName}},\n\nWe're sorry to hear about the damage to your shipment #{{shipmentId}}. We've filed a claim and our team will:\n\n1. Review the damage documentation you provided\n2. Coordinate with the carrier\n3. Process compensation within 5 business days\n\nBest regards,\n{{agentName}}",
        issueType: "Damaged goods",
      },
      {
        name: "Customs Clearance Update",
        subject: "Customs clearance update for your shipment",
        body: "Hi {{customerName}},\n\nYour shipment #{{shipmentId}} is currently in customs. {{customsDetails}}\n\nIf additional documentation is required, we'll reach out with specific instructions.\n\nBest regards,\n{{agentName}}",
        issueType: "Customs",
      },
      {
        name: "Route Change Confirmation",
        subject: "Delivery route change confirmed",
        body: "Hi {{customerName}},\n\nWe've updated the delivery details for shipment #{{shipmentId}}:\n\nNew address: {{newAddress}}\nRevised ETA: {{revisedEta}}\n\nPlease note that route changes may affect delivery timelines.\n\nBest regards,\n{{agentName}}",
        issueType: "Route change",
      },
    ],
    slaTargets: { firstResponseMinutes: 120, resolutionMinutes: 720 },
    isActive: true,
    sortOrder: 6,
  },
];
